name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Image
      run: |
        ECR_URI=$(aws ecr describe-repositories \
          --repository-names predict-api \
          --query 'repositories[0].repositoryUri' \
          --output text)

        docker build -t predict-api -f docker/Dockerfile .
        docker tag predict-api:latest $ECR_URI:latest
        docker push $ECR_URI:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster predict-cluster \
          --service predict-service \
          --force-new-deployment
